### ISSUE TITLE
NoMethodError: undefined method `configure' 

### ISSUE THREAD

**Issue by dilpu** [bborn/communityengine#215]
communityapp apple$ rails -v
Rails 4.0.9
communityapp apple$ ruby -v
## ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

communityapp apple$ bin/rake db:migrate --trace
/Users/apple/.rvm/gems/ruby-2.1.2@global/gems/bundler-1.6.2/lib/bundler.rb:301: warning: Insecure world writable dir /usr/local in PATH, mode 040777
*\* Invoke db:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
NoMethodError: undefined method `configure' for #<Communityapp::Application:0x007f98d0b481b8>
/Users/apple/myapp/communityapp/config/environments/development.rb:1:in`<top (required)>'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in `require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in`block in require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in`require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/engine.rb:591:in `block (2 levels) in <class:Engine>'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/engine.rb:590:in`each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/engine.rb:590:in `block in <class:Engine>'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:30:in`instance_exec'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:30:in `run'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:55:in`block in run_initializers'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:348:in`block (2 levels) in each_strongly_connected_component'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:427:in`each_strongly_connected_component_from'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:44:in`each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:44:in `tsort_each_child'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in`call'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:347:in`block in each_strongly_connected_component'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in`call'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:224:in`tsort_each'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/initializable.rb:54:in`run_initializers'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/application.rb:215:in `initialize!'
/Users/apple/myapp/communityapp/config/environment.rb:5:in`<top (required)>'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in `require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in`block in require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/activesupport-4.0.9/lib/active_support/dependencies.rb:229:in`require'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/application.rb:189:in `require_environment!'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/railties-4.0.9/lib/rails/application.rb:250:in`block in run_tasks_blocks'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in`block in execute'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in`execute'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:201:in`block in invoke_prerequisites'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:in`invoke_prerequisites'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/apple/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in`mon_synchronize'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in`invoke'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in`block in top_level'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in`top_level'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in`standard_exception_handling'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/apple/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in`<top (required)>'
bin/rake:16:in `load'
bin/rake:16:in`<main>'
Tasks: TOP => db:migrate => environment
startupfreak:communityapp apple$

**Comment by vijayj** [comment]
@dilpu - I am getting similar errors with rails 4.0 and ruby 2.1. How did you resolve this issue ?

**Comment by jj5201** [comment]
Same here, any help would be great.
