### ISSUE TITLE
Need for rails 4.1 or possibly 4.2 support

### ISSUE THREAD

**Issue by blehman12** [bborn/communityengine#274]
Has anyone tried to get these tools working with either rails 4.1 or 4.2?  It looks like it is was ported to 4.0 but not after that.  If not and others have interest I would be interestead in participating in that effort.

This is more of a request/comment but I do not see any place else to put the question/request.  If I have done this in the wrong spot please let me know.

--Bob

**Comment by vijayj** [comment]
@t-bullock - do you plan to submit it as a pull request for the master ? I am looking for the same - support for community engine for rails 4.1, ideally rails 4.2. Happy to contribute but would love some pointers on where to start

**Comment by blehman12** [comment]
Not sure this was aimed at me or Trevor, but.

I need to get a bit more educated on how to do things so please read below.


- Trevor sent this message
"

I've tried to get CE working with Rails 4.1. The biggest issue is 
upgrading CE's gems that don't support 4.1 (most notably 
ActsAsTaggableOn <https://github.com/mbleigh/acts-as-taggable-on>). You 
can checkout what I've done so far on my rails4.1 branch 
<https://github.com/t-bullock/communityengine/tree/rails4.1>.
"

If I get the time this weekend I will clone that and see where it gets 
me.  I did look at ActsAsTaggableOn breifly and it looks like it is not 
supported.


My approach for attacking this problem is

- Pull Trevor's code

- see if I can get bundle install to work with 4.1

     - Track plugins that fail
     -  Post my results to the group
     - See if I can get gem owners interested in upgrading
           - See how I can help them
     - Keep working up the stack until getting to CommunityEngine

- After bundle install run the test suite for CommunityEngine and see 
what fails

      - Chase down the issues


I will be happy to post my progress if I make it to this group.  I can 
do that via email or some other mechanism. What ever others feel is best 
- I do not have much experience working in this fashion.   As a result I 
am open for advice on approach and communication techniques or any other 
advice.



--Bob

**Comment by vijayj** [comment]
@blehman12 - thanks for looking into this. I pulled down @t-bullock code for the 4.1 branch and tried to run tests. They failed for me in unit tests that involve acts_as_taggable. I was not sure if these are just failing for me or on that branch.
```
TagsControllerTest#test_should_show_special_character_tag:
NameError: uninitialized constant ActsAsTaggableOn::DefaultParser
```
I used these commands to run the tests


RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
 bundle exec rake test

**Comment by t-bullock** [comment]
@blehman12 - Sounds like a good plan. I'm think all the gems that CE uses should be rails 4.1 compatible, it's just a matter of updating some of them and making sure all tests pass.

@vijayj - I haven't looked at this branch in a while, but I know I tried to update ActsAsTaggable to version 3.0.0, and then started fixing tagging related errors in tests. I never got around to fixing them, so you and @blehman12 might start there.

**Comment by bborn** [comment]
I'm working on getting this working in the edge branch: https://github.com/bborn/communityengine/tree/edge

**Comment by bborn** [comment]
Edge branch now has passing tests on Rails 4.1 with Ruby 2.

**Comment by bborn** [comment]
@t-bullock thanks for your work on your 4.1 branch - I started there and fixed up ActsAsTaggable problems.

**Comment by blehman12** [comment]
Oh, cool, thanks - I will switch over to that as soon as I can.

**Comment by t-bullock** [comment]
Awesome work, thanks!
