### ISSUE TITLE
general question: events owner

### ISSUE THREAD

**Issue by mattherick** [bborn/communityengine#277]
Why is it only for admins allowed to create events? 

In my opinion every user should be able to create events and get his own event direction like your-domain.com/users/username/events and own ical subscription possibility..

What do you think about this idea?

**Comment by bborn** [comment]
No good reason for it. I'd be happier if it was configurable (i.e. specify the application config who should be allowed to create events).

**Comment by mattherick** [comment]
But if you generate an own events section for every user it also could be possible to invite special friends for different events and only these will see the events - like an facebook event.. or something similar? or could this be a completely new feature?
