### ISSUE TITLE
configatron default photo settings not working

### ISSUE THREAD

**Issue by mattherick** [bborn/communityengine#279]
With the default setting of the photos section in application_config.rb:

    configatron.configure_from_hash(
        :photo => {
          :missing_thumb => '/assets/icon_missing_thumb.gif',
          :missing_medium => "/assets/icon_missing_medium.gif",
        }
    )

I always get following error:

    "NetworkError: 404 Not Found - http://staging.my-domain.com/assets/icon_missing_medium.gif"

My setup:

    gem 'rails', '4.0.13'
    gem 'community_engine', :git => 'https://github.com/bborn/communityengine', :branch => 'master'

How could this be fixed for using the normal asset pipeline?

**Comment by bborn** [comment]
Hmmm... my guess is that you just don't have `icon_missing_medium.gif` added to the list of assets Rails precompiles (in `production.rb`). I suppose we could have the CE engine add that asset...

**Comment by mattherick** [comment]
Hmmm but this is a normal image, isn't it? Why do I have to add it? It is already in the images folder, I simple use the default settings from the CE..

**Comment by bborn** [comment]
Any asset that you reference at /assets/* needs to be precompiled (or else
you need to tell Rails to serve assets when a precompiled one is
missed: config.assets.compile = true)

**Comment by bborn** [comment]
Fixed by #282

**Comment by mattherick** [comment]
#282 does not fix this problem :-)..

**Comment by bborn** [comment]
Sorry! Got confused about which asset path you changed. Did you try setting `config.assets.compile = true` in production.rb?
