### ISSUE TITLE
Toggle Featured Writer Route Missing

### ISSUE THREAD

**Issue by larouxn** [bborn/communityengine#283]
When you click the Toggle Featured writer button ona user's profile a PUT request is fired off to /users/admin123/toggle_featured. Not sure if this is specific to my setup but I am receiving:
`ActionController::RoutingError (No route matches [PUT] "/users/admin123/toggle_featured"):`

Is anybody experiencing this issue?

**Comment by mattherick** [comment]
+ 1
I will take a look at this problem..just seems to be a PUT - PATCH change.. I will provide a PR soon.

**Comment by larouxn** [comment]
Okay, awesome!

**Comment by mattherick** [comment]
I fixed the problem..but it seems that there are more PUT - PATCH problems.. I will take a close look and provide one PR, if I solved all of these cases..

**Comment by mattherick** [comment]
https://github.com/bborn/communityengine/pull/282 -> this contains the fix for this problem (and also other fixes)

**Comment by mattherick** [comment]
I think this issue could be closed..it´s fixed in the current master.
