### ISSUE TITLE
Error when editing a comment

### ISSUE THREAD

**Issue by blehman12** [bborn/communityengine#287]
When attempting to edit a user comment on their profile as an admin user the edit button the next page renders as like what is shown below.  I think it has something to do with the file
app/views/comments/edit.js.erb
The line
  $('#comment-<%= @comment.id %>').replaceWith("<%= escape_javascript(render :partial => 'comments/comment', :formats => [:html], :locals => {:comment => @comment, :highlighted => true}) %>")

But right now it is above my skill level to debug this.  Though I did spend several hours trying.  Any advice on how to fix this?  Do you need anymore information to help debug.

Page ouput

http://localhost:3000/Photo/2/comments/2/edit

ActionController::UnknownFormat in CommentsController#edit
ActionController::UnknownFormat

Rails.root: /home/blehman/rails_40_proj/testzzz
Application Trace | Framework Trace | Full Trace

Request

Parameters:

{"commentable_type"=>"Photo",
 "commentable_id"=>"2",
 "id"=>"2"}

Toggle session dump
Toggle env dump
Response

Headers:

None

Thanks in advance for the help.
--Bob

**Comment by bborn** [comment]
are you using turbolinks?

**Comment by blehman12** [comment]
I believe so - here is an output from gem list

gem list turbolinks

*** LOCAL GEMS ***

turbolinks (2.5.3, 2.5.2, 2.2.2, 1.3.0, 1.1.1)


Should I be?

--Bob

**Comment by bborn** [comment]
If you're on the master branch of CE, then no, you shouldn't include turbolinks (or if you do, be prepared to try to fix all the things it breaks). Edge CE should be (mostly) compatibly with Turbolinks, but it's not well tested yet.
