### ISSUE TITLE
Occasionally the user dropdown menu doesn't appear

### ISSUE THREAD

**Issue by larouxn** [bborn/communityengine#290]
The user's dropdown menu in the top right corner works well when it works.

However, occasionally you will click the the user's name and the dropdown will not appear, will not trigger. I've had to then navigate to some other page, I usually go to Home, and then click the name again which successfully triggers the dropdown menu.

**Comment by bborn** [comment]
Hmm...  I wonder if this is a turbolinks thing. Are you on Rails 4?

**Comment by larouxn** [comment]
Yup. Rails 4.

**Comment by larouxn** [comment]
I investigated the issue more thoroughly. It seems like if you click any of the page links in the nav, that page will load but the dropdown will not work. If you click the same nav link again, the dropdown will work. Refreshing normally does not fix it.

**Comment by bborn** [comment]
#292
