### ISSUE TITLE
Commenting on Event Breaks Show

### ISSUE THREAD

**Issue by larouxn** [bborn/communityengine#292]
In my testing, commenting on an event breaks the Show button/action for that event. If you comment on said event, click back, then click show you will receive this on the server side:
```ActionView::Template::Error (undefined method `user_event_url' for #<#<Class:0x007fed55adc448>:0x007fed59b57f68>):```

Why is `user_event_url' surrounded by a grave accent and an apostrophe?

And this on the frontend:
![screen shot 2015-01-26 at 13 58 10](https://cloud.githubusercontent.com/assets/1557529/5906186/b21b87fc-a563-11e4-8242-9ea0cd287632.png)

**Comment by larouxn** [comment]
Just tested again with a fresh setup, the ```undefined method `user_event_url'``` issue upon commenting that breaks the show action persists.

**Comment by bborn** [comment]
Are you loading turbolinks? For now CE is not compatible with Turbolinks, so if you're loading it in your application somewhere, it will break lots of CE functionality.

**Comment by larouxn** [comment]
I was indeed loading Turbolinks. I removed all Turbolinks requires/gem includes from my project. Removing Turbo did fix my dropdown and text box issues. However, the event commenting issue is still prevalent.
