### ISSUE TITLE
bin/rake error

### ISSUE THREAD

**Issue by Marsupio** [bborn/communityengine#295]
bin/rake community_engine:install:migrations gives this error message:

rake aborted!
LoadError: cannot load such file -- aws/s3
/home/jorge/railsprojects/community_engine/config/application.rb:7:in `<top (required)>'
/home/jorge/railsprojects/community_engine/Rakefile:4:in `require'
/home/jorge/railsprojects/community_engine/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by jj5201** [comment]
include the following in your Gemfile: gem 'aws-s3'

**Comment by bborn** [comment]
Yeah, this is now fixed in master.

**Comment by cpipero** [comment]
Just ran the command and had to update the GemFile to make it work. Please verify the fix. Thanks for posting the solution.
