### ISSUE TITLE
is binstubs option needed?

### ISSUE THREAD

**Issue by tmaekawa** [bborn/communityengine#296]
Hi, I'm newbee to community engine. I'm reading the source code and try to playing with it.
I think I had done setup as the installing guide in this repository says, but there are some strange things happnening, I guess.
the message as bellow is shown when I type 'rails console':

---------------------------------------------------------------------------------------
[vagrant@localhost testapp]$ rails console
Looks like your app's ./bin/rails is a stub that was generated by Bundler.

In Rails 4, your app's bin/ directory contains executables that are versioned
like any other source code, rather than stubs that are generated on demand.

Here's how to upgrade:

  bundle config --delete bin    # Turn off Bundler's stub generator
  rake rails:update:bin         # Use the new Rails 4 executables
  git add bin                   # Add bin/ to source control

You may need to remove bin/ from your .gitignore as well.

When you install a gem whose executable you want to use in your app,
generate it and add it to source control:

  bundle binstubs some-gem-name
  git add bin/new-executable

sh: git: command not found
---------------------------------------------------------------------------------------

What this means??  and I want to know how to avoid this.

My enviroment:
centos 6.6 - with vagrant 1.7.2
rails  - 4.0.2
community engine  - download mastar.zip about a month ago

I'll apologize if I should write questions like this at other places...I'm new to github too.

thanks.

**Comment by bborn** [comment]
Looks like you don't have git installed. It's not technically required to use CE, but if you're trying to run `git add` without having git, you're going to have problems.
