### ISSUE TITLE
Activation email not getting sent

### ISSUE THREAD

**Issue by Ary33** [bborn/communityengine#297]
Forgive my ignorance but... I am not receiving the activation email that is supposed to be sent. I don't know if it is because I am on localhost or not. I'd like to think it was that simple. It tells me that it was sent and I've resent it various times but still nothing. Does anyone have any idea of how to fix this?

**Comment by t-bullock** [comment]
If you're running CommunityEngine in development mode, the email will simply show up in your terminal. Scroll up a bit in your terminal and look for something like this:

Sent mail to user41@example.com (14.1ms)
Date: Wed, 29 Jul 2015 15:20:22 -0400
From: The CommunityEngine Team <support@example.com>
To: user41@example.com
Message-ID: <53b92776726ce_36293ffe35621488616dc@t-bullock.local.mail>
Subject: [CommunityEngine] Please activate your new CommunityEngine account
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Welcome to CommunityEngine, user41!
Your account has been created, but you still need to activate it before you can log in.
Here's your info:

  Your username: user41

Use this link to activate your account:

  http://example.com/users/4b9aa6e2fbc2a3403512ddc8b6b37294f028b0c5/activate

Can't click the link? Just copy and paste it into your address bar.

Questions? Easy: support@example.com.

We hope to see you on CommunityEngine soon!
The CommunityEngine team

**Comment by Ary33** [comment]
Thank so much for your time and answer. I'm going to give it a go right now! I've been trying to write my own social network site for a few months now, (without a lot of success), so I want to thank the Community Engine Team for all your hard work coding! I'm trying to do miracles with your engine so I'm sure you'll get more questions from me. It's nice to know that you're there responding to the doubts us noobs have. Thanks again :)
