### ISSUE TITLE
Paperclip::Errors::NotIdentifiedByImageMagickError

### ISSUE THREAD

**Issue by Ary33** [bborn/communityengine#298]
I'm trying everything I can before posting more issues believe me. Posting here is my last resort. 

I`m getting this error when I try to upload a profile photo to Community Engine and I can't seem to fix it. 

Things I've tried:

I tried to add the :path and :url as prescribed in the post install message though I'm not sure if I am doing right. I tried copying the code exactly as it shows 

:path => ":rails_root/public/system/:attachment/:id/:style/:filename", :url => "/system/:attachment/:id/:style/:filename"

And I also tried to substitute :rails_root for my actual root on my computer and both are not helping

I also tried all different file types, jpg, png, gif, etc and nothing

And finally I tried simplifying the file names to avoid any possible conflict such as 1.jpg or 1.png and still nothing.

I also verified my versions of Paperclip and Imagemagick and indeed they were a more recent version than what CE requires... I got excited now thinking that this had to be it but when I uploaded the correct versions and fixed up my gem and gem lock files, restarted the server and everything, I STILL GOT THE SAME ERROR.

So here I am at the end of my rope hoping you can help. Thanks in advance for your time CE team!

UPDATE: The above was the profile photo. I just went in to try to upload a photo to an album and it seemed to upload only it doesn't display the photo just that little default square thingy that shows when there should be an image but there isn't... so I inspected the element in Google Chrome and copied the URL to the image, http://localhost:3000/system/photos/large/1.jpg?1438449483, and pasted it in the address bar and received this error:

Routing Error
No route matches [GET] "/system/photos/large/1.jpg

I tried changing the routes around but to no avail. I hope this info helps you help me solve this problem :)

**Comment by mattherick** [comment]
Did you check out following issue already?

https://github.com/thoughtbot/paperclip/issues/1405

**Comment by Ary33** [comment]
Yeah mattherick. I've been through that like three times now but went back to it at your suggestion. Added config paths to development and application rbs and everything but still nothing. There is no style for the has_attached_file line, in CE it has the "configatron.photo.paperclip_options.to_hash" attribute if that's what you call it. So, thanks for the help, I'll keep trying in the meantime.

I'm on Windows 7 by the way :/
