### ISSUE TITLE
rake aborted on  db:migrate

### ISSUE THREAD

**Issue by cpipero** [bborn/communityengine#299]
CE 3.0.0 on Rails 4.x

Got the following error trying to install, made it without much pain until the command
`$ bin/rake db:migrate`

get the following output:

>/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.0/lib/active_support/values/time_zone.rb:282: >warning: circular argument reference - now
>** Invoke db:migrate (first_time)
>** Invoke environment (first_time)
>** Execute environment
>rake aborted!
>NoMethodError: undefined method `configure' for #<Workspace::Application:0x00000003f6eac0>
>/home/ubuntu/workspace/config/environments/development.rb:1:in `<top (required)>'
>/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in >`require'
>/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in >`block in require'
>/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in >`load_dependency'
>/usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in >`require'
>/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.0/lib/rails/engine.rb:591:in `block (2 levels) in ><class:Engine>'
>/usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.0/lib/rails/engine.rb:590:in `each'

**Comment by priyankorv** [comment]
Got this error at migration:
C:\Sites\rails_project\abc>rake db:migrate
DL is deprecated, please use Fiddle
rake aborted!
NoMethodError: undefined method `application' for Abc:Module
C:/Sites/rails_project/abc/config/environments/development.rb:1:in `<top (re
quired)>'
C:/Sites/rails_project/abc/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
