### ISSUE TITLE
New Project - getting undefined method `validators_on' for Ransack::Search:Class

### ISSUE THREAD

**Issue by balgarath** [bborn/communityengine#304]
First, thanks for all your work on CE!

[EDIT] also getting this error on the admin/tags page[ENDEDIT]

I wanna say in my research I saw the Issue you opened here in the bootstrap-forms repo a few months ago on the issue: https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/203

I'm assuming that since you were asking about this issue that I shouldn't be getting the error?  Maybe some kind of dependency issue?  I haven't really used Rails since before 3.0 came out.

This is a new project in Rails 4.0.13 I'm just getting going and haven't added any of my own code yet.  I'm getting the error on the user post manage page:

I, [2016-01-02T06:54:51.955508 #8636]  INFO -- : Completed 500 Internal Server Error in 24ms
F, [2016-01-02T06:54:51.959215 #8636] FATAL -- : 
ActionView::Template::Error (undefined method `validators_on' for Ransack::Search:Class):
    3: -widget do
    4:   %h3=:search.l
    5:   = bootstrap_form_for @search, :url => manage_user_posts_path(current_user), :html => {:class => "form"} do |f|
    6:     = f.text_field :title_cont, :label => :title.l
    7: 
    8:     = f.select :category_id_eq, Category.all.collect{|c| [c.name, c.id]}, :include_blank => true, :label => :category.l
    9:     = f.select :published_as_eq, [['Published','live'], ['Draft','draft']], :include_blank => true, :label => :status.l
  vendor/bundle/ruby/2.2.0/gems/bootstrap_form-2.3.0/lib/bootstrap_form/form_builder.rb:266:in`required_attribute?'
  vendor/bundle/ruby/2.2.0/gems/bootstrap_form-2.3.0/lib/bootstrap_form/form_builder.rb:336:in `generate_label'
  vendor/bundle/ruby/2.2.0/gems/bootstrap_form-2.3.0/lib/bootstrap_form/form_builder.rb:181:in`block in form_group'

...
...
...

**Comment by bborn** [comment]
@balgarath which versions of bootstrap_form and ransack are in your Gemfile.lock?
