### ISSUE TITLE
Event link not rendering

### ISSUE THREAD

**Issue by sqlsolver** [bborn/communityengine#305]
The home page of http://www.ebspug.org only renders in IE, Chrome and FireFox show the following error:
![image](https://cloud.githubusercontent.com/assets/4545063/12228896/3caea4a8-b7f6-11e5-8585-f08aa5901c01.png)
The error says the URL is not allowed by the app's settings however the issue is browser specific.

**Comment by bborn** [comment]
Renders fine for me in Chrome and FF. I don’t think this issue is
CE-related.
