### ISSUE TITLE
Is this still an active project ?

### ISSUE THREAD

**Issue by simonstearn** [bborn/communityengine#306]
Hi Guys

This looks really useful for something I am working on, but I cant get it working with Rails 4.1 by following the instructions (even if I build a local gem from the edge version).  I could not get the heroku demo app working either - cannot get all the older dependancies now.

Are you planning any further updates ?

Thanks

Simon

**Comment by bborn** [comment]
Hi Simon,
It's not super-active, but also not dead. The master branch, works with Rails 4.0.x (as noted in the README). Edge branch (https://github.com/bborn/communityengine/tree/edge) should work fine on 4.1 (@t-bullock has done most of the work there).

**Comment by simonstearn** [comment]
Hi - I am getting an error install against Rails 4.0.  Here is the terminal trace of an installation following an rvm implode.. (the burger is my prompt, sorry):

~/Dropbox/Proslogia/Code/Ruby 🍔  \curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles
Turning on auto dotfiles mode.
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Installing RVM to /Users/simon/.rvm/
    Removing rvm PATH line from /Users/simon/.mkshrc /Users/simon/.profile /Users/simon/.bashrc /Users/simon/.zshrc.
    Adding rvm PATH line to /Users/simon/.profile /Users/simon/.mkshrc /Users/simon/.bashrc /Users/simon/.zshrc.
    Removing rvm loading line from /Users/simon/.profile /Users/simon/.bash_profile /Users/simon/.zlogin.
    Adding rvm loading line to /Users/simon/.profile /Users/simon/.bash_profile /Users/simon/.zlogin.
Installation of RVM in /Users/simon/.rvm/ is almost complete:

  * To start using RVM you need to run `source /Users/simon/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# Simon Stearn,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/simon/.bash_profile':

      source ~/.profile

~/Dropbox/Proslogia/Code/Ruby 🍔  rvm install 2.0
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.0.0-p643.tar.bz2
Checking requirements for osx.
Updating certificates in '/usr/local/etc/openssl/cert.pem'.
Requirements installation successful.
ruby-2.0.0-p643 - #configure
ruby-2.0.0-p643 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6109k  100 6109k    0     0   634k      0  0:00:09  0:00:09 --:--:--  718k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.0.0-p643 - #validate archive
ruby-2.0.0-p643 - #extract
ruby-2.0.0-p643 - #validate binary
ruby-2.0.0-p643 - #setup
ruby-2.0.0-p643 - #gemset created /Users/simon/.rvm/gems/ruby-2.0.0-p643@global
ruby-2.0.0-p643 - #importing gemset /Users/simon/.rvm/gemsets/global.gems..............................
ruby-2.0.0-p643 - #generating global wrappers........
ruby-2.0.0-p643 - #gemset created /Users/simon/.rvm/gems/ruby-2.0.0-p643
ruby-2.0.0-p643 - #importing gemsetfile /Users/simon/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.0.0-p643 - #generating default wrappers........
Updating certificates in '/etc/openssl/cert.pem'.
simon password required for 'command tee /etc/openssl/cert.pem': 
~/Dropbox/Proslogia/Code/Ruby 🍔  rvm use 2.0
Using /Users/simon/.rvm/gems/ruby-2.0.0-p643
~/Dropbox/Proslogia/Code/Ruby 🍔  rvm default 2.0
~/Dropbox/Proslogia/Code/Ruby 🍔  which ruby
/Users/simon/.rvm/rubies/ruby-2.0.0-p643/bin/ruby
~/Dropbox/Proslogia/Code/Ruby 🍔  which gem
/Users/simon/.rvm/rubies/ruby-2.0.0-p643/bin/gem
~/Dropbox/Proslogia/Code/Ruby 🍔  gem install rails -v 4.0
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-0.3.46.gem (100%)
Successfully installed tzinfo-0.3.46
Fetching: activesupport-4.0.0.gem (100%)
Successfully installed activesupport-4.0.0
Fetching: builder-3.1.4.gem (100%)
Successfully installed builder-3.1.4
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: rack-1.5.5.gem (100%)
Successfully installed rack-1.5.5
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: actionpack-4.0.0.gem (100%)
Successfully installed actionpack-4.0.0
Fetching: mime-types-1.25.1.gem (100%)
Successfully installed mime-types-1.25.1
Fetching: polyglot-0.3.5.gem (100%)
Successfully installed polyglot-0.3.5
Fetching: treetop-1.4.15.gem (100%)
Successfully installed treetop-1.4.15
Fetching: mail-2.5.4.gem (100%)
Successfully installed mail-2.5.4
Fetching: actionmailer-4.0.0.gem (100%)
Successfully installed actionmailer-4.0.0
Fetching: activemodel-4.0.0.gem (100%)
Successfully installed activemodel-4.0.0
Fetching: activerecord-deprecated_finders-1.0.4.gem (100%)
Successfully installed activerecord-deprecated_finders-1.0.4
Fetching: arel-4.0.2.gem (100%)
Successfully installed arel-4.0.2
Fetching: activerecord-4.0.0.gem (100%)
Successfully installed activerecord-4.0.0
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: railties-4.0.0.gem (100%)
Successfully installed railties-4.0.0
Fetching: hike-1.2.3.gem (100%)
Successfully installed hike-1.2.3
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: sprockets-2.12.4.gem (100%)
Successfully installed sprockets-2.12.4
Fetching: sprockets-rails-2.0.1.gem (100%)
Successfully installed sprockets-rails-2.0.1
Fetching: rails-4.0.0.gem (100%)
Successfully installed rails-4.0.0
Parsing documentation for i18n-0.7.0
Installing ri documentation for i18n-0.7.0
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
Parsing documentation for thread_safe-0.3.5
Installing ri documentation for thread_safe-0.3.5
Parsing documentation for tzinfo-0.3.46
Installing ri documentation for tzinfo-0.3.46
Parsing documentation for activesupport-4.0.0
unable to convert "\x80" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping
Installing ri documentation for activesupport-4.0.0
Parsing documentation for builder-3.1.4
/Users/simon/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rdoc/parser.rb:87: warning: Unsupported encoding : ignored
/Users/simon/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/rdoc/parser.rb:87: warning: Unsupported encoding  ignored
Installing ri documentation for builder-3.1.4
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for rack-1.5.5
Installing ri documentation for rack-1.5.5
Parsing documentation for rack-test-0.6.3
Installing ri documentation for rack-test-0.6.3
Parsing documentation for actionpack-4.0.0
Installing ri documentation for actionpack-4.0.0
Parsing documentation for mime-types-1.25.1
Installing ri documentation for mime-types-1.25.1
Parsing documentation for polyglot-0.3.5
Installing ri documentation for polyglot-0.3.5
Parsing documentation for treetop-1.4.15
Installing ri documentation for treetop-1.4.15
Parsing documentation for mail-2.5.4
unable to convert "\x80" from ASCII-8BIT to UTF-8 for lib/mail/values/unicode_tables.dat, skipping
Installing ri documentation for mail-2.5.4
Parsing documentation for actionmailer-4.0.0
Installing ri documentation for actionmailer-4.0.0
Parsing documentation for activemodel-4.0.0
Installing ri documentation for activemodel-4.0.0
Parsing documentation for activerecord-deprecated_finders-1.0.4
Installing ri documentation for activerecord-deprecated_finders-1.0.4
Parsing documentation for arel-4.0.2
Installing ri documentation for arel-4.0.2
Parsing documentation for activerecord-4.0.0
Installing ri documentation for activerecord-4.0.0
Parsing documentation for bundler-1.11.2
Installing ri documentation for bundler-1.11.2
Parsing documentation for thor-0.19.1
Installing ri documentation for thor-0.19.1
Parsing documentation for railties-4.0.0
Installing ri documentation for railties-4.0.0
Parsing documentation for hike-1.2.3
Installing ri documentation for hike-1.2.3
Parsing documentation for tilt-1.4.1
Installing ri documentation for tilt-1.4.1
Parsing documentation for sprockets-2.12.4
Installing ri documentation for sprockets-2.12.4
Parsing documentation for sprockets-rails-2.0.1
Installing ri documentation for sprockets-rails-2.0.1
Parsing documentation for rails-4.0.0
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/belongs_to.png, skipping
unable to convert "\xF4" from ASCII-8BIT to UTF-8 for guides/assets/images/book_icon.gif, skipping
unable to convert "\x91" from ASCII-8BIT to UTF-8 for guides/assets/images/bullet.gif, skipping
unable to convert "\xF5" from ASCII-8BIT to UTF-8 for guides/assets/images/chapters_icon.gif, skipping
unable to convert "\xF5" from ASCII-8BIT to UTF-8 for guides/assets/images/check_bullet.gif, skipping
unable to convert "\xF4" from ASCII-8BIT to UTF-8 for guides/assets/images/credits_pic_blank.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/csrf.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/edge_badge.png, skipping
unable to convert "\x9E" from ASCII-8BIT to UTF-8 for guides/assets/images/favicon.ico, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/feature_tile.gif, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/footer_tile.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/fxn.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/challenge.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/confirm_dialog.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/forbidden_attributes_for_new_post.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/form_with_errors.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/index_action_with_edit_link.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/new_post.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/post_with_comments.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/rails_welcome.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/routing_error_no_controller.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/routing_error_no_route_matches.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/show_action_for_posts.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/template_is_missing_posts_new.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/undefined_method_post_path.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/unknown_action_create_for_posts.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/getting_started/unknown_action_new_for_posts.png, skipping
unable to convert "\xF0" from ASCII-8BIT to UTF-8 for guides/assets/images/grey_bullet.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/habtm.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/has_many.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/has_many_through.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/has_one.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/has_one_through.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/header_backdrop.png, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/header_tile.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_html_safe.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_localized_pirate.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_translated_en.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_translated_pirate.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_translation_missing.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/i18n/demo_untranslated.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/1.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/10.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/11.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/12.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/13.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/14.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/15.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/2.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/3.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/4.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/5.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/6.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/7.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/8.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/callouts/9.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/caution.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/example.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/home.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/important.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/next.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/note.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/prev.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/tip.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/up.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/icons/warning.png, skipping
unable to convert "\xFF" from ASCII-8BIT to UTF-8 for guides/assets/images/jaimeiniesta.jpg, skipping
unable to convert "\xF5" from ASCII-8BIT to UTF-8 for guides/assets/images/nav_arrow.gif, skipping
unable to convert "\xFF" from ASCII-8BIT to UTF-8 for guides/assets/images/oscardelben.jpg, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/polymorphic.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/radar.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/rails4_features.png, skipping
unable to convert "\xFF" from ASCII-8BIT to UTF-8 for guides/assets/images/rails_guides_kindle_cover.jpg, skipping
unable to convert "\xEC" from ASCII-8BIT to UTF-8 for guides/assets/images/rails_guides_logo.gif, skipping
unable to convert "\x8C" from ASCII-8BIT to UTF-8 for guides/assets/images/rails_logo_remix.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/session_fixation.png, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_grey.gif, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_info.gif, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_note.gif, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_red.gif, skipping
unable to convert "\x80" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_yellow.gif, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for guides/assets/images/tab_yellow.png, skipping
unable to convert "\xFF" from ASCII-8BIT to UTF-8 for guides/assets/images/vijaydev.jpg, skipping
Installing ri documentation for rails-4.0.0
27 gems installed
~/Dropbox/Proslogia/Code/Ruby 🍔  rails -v
Rails 4.0.0
~/Dropbox/Proslogia/Code/Ruby 🍔  which rails
/Users/simon/.rvm/gems/ruby-2.0.0-p643/bin/rails
~/Dropbox/Proslogia/Code/Ruby 🍔  ls -la
total 1728
drwxr-xr-x@  8 simon  staff     272  1 Mar 20:01 .
drwxr-xr-x@ 15 simon  staff     510 27 Feb 13:37 ..
-rw-r--r--@  1 simon  staff    8196 28 Feb 16:44 .DS_Store
-rw-r--r--@  1 simon  staff   74232 28 Feb 15:58 ce-heroku-master.zip
drwxr-xr-x@ 20 simon  staff     680 28 Feb 17:14 cohesia_community
drwxr-xr-x@ 25 simon  staff     850 28 Feb 16:59 communityengine-edge
-rw-r--r--@  1 simon  staff  790653 28 Feb 16:43 communityengine-edge.zip
drwxr-xr-x@ 25 simon  staff     850 28 Feb 08:56 communityengine-master
~/Dropbox/Proslogia/Code/Ruby 🍔  rails new test1
      create  
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
      create  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/secret_token.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies......
Installing rake 10.5.0
Using i18n 0.7.0
Installing minitest 4.7.5
Using multi_json 1.11.2
Using thread_safe 0.3.5
Using tzinfo 0.3.46
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using mime-types 1.25.1
Using polyglot 0.3.5
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using bundler 1.11.2
Installing coffee-script-source 1.10.0
Installing execjs 2.6.0
Using thor 0.19.1
Using hike 1.2.3
Installing json 1.8.3 with native extensions
Using tilt 1.4.1
Installing sass 3.2.19
Installing sqlite3 1.3.11 with native extensions
Using activesupport 4.0.0
Using rack-test 0.6.3
Using treetop 1.4.15
Installing coffee-script 2.4.1
Installing rdoc 4.2.2
Installing uglifier 2.7.2
Using sprockets 2.12.4
Using activemodel 4.0.0
Installing jbuilder 1.5.3
Using actionpack 4.0.0
Using mail 2.5.4
Installing sdoc 0.4.1
Using activerecord 4.0.0
Using railties 4.0.0
Using sprockets-rails 2.0.1
Using actionmailer 4.0.0
Installing coffee-rails 4.0.1
Installing jquery-rails 3.1.4
Installing sass-rails 4.0.5
Using rails 4.0.0
Installing turbolinks 2.5.3
Bundle complete! 9 Gemfile dependencies, 43 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
~/Dropbox/Proslogia/Code/Ruby 🍔  cd test1
~/Dropbox/Proslogia/Code/Ruby/test1 🍔  vi Gemfile
~/Dropbox/Proslogia/Code/Ruby/test1 🍔  cat Gemfile
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'community_engine', '~> 3.0.0'
~/Dropbox/Proslogia/Code/Ruby/test1 🍔  bundle install
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "sprockets":
  In snapshot (Gemfile.lock):
    sprockets (= 2.12.4)

  In Gemfile:
    community_engine (~> 3.0.0) was resolved to 3.0.0, which depends on
      sprockets (~> 2.10.0)

    community_engine (~> 3.0.0) was resolved to 3.0.0, which depends on
      sass-rails (~> 4.0.0) was resolved to 4.0.5, which depends on
        sprockets (< 3.0, ~> 2.8)

    rails (= 4.0.0) was resolved to 4.0.0, which depends on
      sprockets-rails (~> 2.0.0) was resolved to 2.0.1, which depends on
        sprockets (~> 2.8)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
~/Dropbox/Proslogia/Code/Ruby/test1 🍔

**Comment by simonstearn** [comment]
Hi - if I understand this correctly the issue is with the conflict in version requirements from sass-rails and community_engine ?

**Comment by simonstearn** [comment]
Hi

I added this line to the top of my Gemfile
```
gem 'sprockets', '~> 2.10.0'
```
and this line to the bottom:
```
gem 'aws-s3'
```

And things are working.

Cheers

Simon
