### ISSUE TITLE
Supporting Rails 4.2.x?

### ISSUE THREAD

**Issue by wingtonbrito** [bborn/communityengine#309]
Just wondering when will it be release. Support for Rails 4.2.x

**Comment by t-bullock** [comment]
Give the edge branch a try. I just made some updates for Rails 4.2.

**Comment by wingtonbrito** [comment]
Thanks for the quick response and the fixes!! Truly appreciate it.  I was able to get it to run with ruby 2.0.0 and rails 4.2 and a few tweaks** . I'll keep playing with it. Will see how it goes with ruby 2.3. 

**tweaks: Needed to include these two lines on config/initializers/assets.rb:
```
Rails.application.config.assets.precompile += %w( community_engine.css )
Rails.application.config.assets.precompile += %w( community_engine.js )
```

**Comment by Ethan-Rivas** [comment]
I was going to start to cry, thanks @wingtonbrito
