### ISSUE TITLE
Rails 4.2 AbsoluteAssetPathError

### ISSUE THREAD

**Issue by digitalronin** [bborn/communityengine#311]
Running the edge branch with rails 4.2, I get errors whenever the site tries to render the default missing_thumb image;

    Sprockets::Rails::Helper::AbsoluteAssetPathError - Asset names passed to helpers should not include the "/assets/" prefix. Instead of "/assets/icon_missing_thumb.gif", use "icon_missing_thumb.gif":

To fix this, I've done the following;

* copy icon_missing_thumb.gif and icon_missing_medium.gif to my Rails app's app/assets/images directory
* Added the following lines to my config/application_config.rb file

    configatron.photo.missing_thumb  = "icon_missing_thumb.gif"
    configatron.photo.missing_medium = "icon_missing_medium.gif"

There is probably a smarter way to do this, but I thought I would mention it here in case anyone else is having the same problem.

David

**Comment by t-bullock** [comment]
What version of sprockets are you using? I wonder if something changed in a newer version.

**Comment by t-bullock** [comment]
The edge branch should be fixed now.
