### ISSUE TITLE
Support higher version of ruby?

### ISSUE THREAD

**Issue by taro-k** [bborn/communityengine#314]
README.markdown says:

Requirements:
- RUBY  2.0.x

but .travis.yml says
rvm
- 2.3.1

Is it OK to use Ruby 2.3.1?

Related information:
https://www.ruby-lang.org/en/downloads/
In security maintenance phase (will EOL soon!):
    Ruby 2.1.10
Not maintained anymore (EOL):
    Ruby 2.0.0-p648

**Comment by taro-k** [comment]
I treat this matter in my forked repo and close here.
https://github.com/taro-k/communityengine/issues/1

**Comment by taro-k** [comment]
@t-bullock Hello. I found your commit https://github.com/bborn/communityengine/commit/28cada7491e1bc751ebdd0d47891090fbf038aa6 .
Why did you re-add and set back to Ruby-2.0.0 which is already out of security fix?

**Comment by t-bullock** [comment]
I guess I didn't realize support for 2.0 had ended at that point. You can remove it.

**Comment by taro-k** [comment]
@t-bullock OK, thx, that's fine, but I think such drop should be done for the new branch after restructuring branches I suggested here: https://github.com/bborn/communityengine/pull/324
