### ISSUE TITLE
[Need to fix] Bump acts-as-taggable-on ~> 4.0.0

### ISSUE THREAD

**Issue by taro-k** [bborn/communityengine#322]
This is not only for making gems fresh but also the road to rails-5.0.
https://github.com/taro-k/communityengine/commit/5a055151098c346b81f651b820a914c3e38cb5e2

Can someone fix this errors?
https://travis-ci.org/taro-k/communityengine/builds/166190742

Ref:
https://github.com/mbleigh/acts-as-taggable-on/blob/master/CHANGELOG.md
Only "Fixes" after 3.4.4 until 4.0.0.

**Comment by t-bullock** [comment]
I think I tried to bump up acts-as-taggable to a higher version at one point, but couldn't fix all the errors. I don't think I'll have time in the near future, but you're welcome to take a stab at it. Maybe @bborn can take a look?
